import {NextUIProvider} from "@nextui-org/react";
import CustomNavbar from '@/components/ui/HomeNavbar'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/Footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OK7 Technical Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark text-foreground`}>
        <CustomNavbar />
        {children}
        <Footer />
      </body>
    </html>

  );
}
